export enum OathName {
  // Tier 1 - Easy (2-3 PV) - 20 cards
  OATH_HARVEST_GRAIN = 'Oath: Harvest Grain',
  OATH_CLEAR_LAND = 'Oath: Clear Land',
  OATH_GATHER_STONE = 'Oath: Gather Stone',
  OATH_TRADE_GOODS = 'Oath: Trade Goods',
  OATH_BUILD_WORKSHOP = 'Oath: Build Workshop',
  OATH_RECRUIT_WARRIOR = 'Oath: Recruit Warrior',
  OATH_STUDY_RUNES = 'Oath: Study Runes',
  OATH_BREW_ALE = 'Oath: Brew Ale',
  OATH_PLANT_ORCHARD = 'Oath: Plant Orchard',
  OATH_FISH_WATERS = 'Oath: Fish Waters',
  OATH_MINE_ORE = 'Oath: Mine Ore',
  OATH_WEAVE_CLOTH = 'Oath: Weave Cloth',
  OATH_TEND_ANIMALS = 'Oath: Tend Animals',
  OATH_CARVE_WOOD = 'Oath: Carve Wood',
  OATH_FORAGE_FOREST = 'Oath: Forage Forest',
  OATH_PRESERVE_FOOD = 'Oath: Preserve Food',
  OATH_SHARPEN_TOOLS = 'Oath: Sharpen Tools',
  OATH_REPAIR_EQUIPMENT = 'Oath: Repair Equipment',
  OATH_TEND_FIRE = 'Oath: Tend Fire',
  OATH_GATHER_HERBS = 'Oath: Gather Herbs',

  // Tier 2 - Medium (4-6 PV) - 25 cards
  OATH_ESTABLISH_TRADE = 'Oath: Establish Trade',
  OATH_DEFEND_BORDER = 'Oath: Defend Border',
  OATH_NEGOTIATE_PEACE = 'Oath: Negotiate Peace',
  OATH_SPREAD_FAITH = 'Oath: Spread Faith',
  OATH_BUILD_TOWER = 'Oath: Build Tower',
  OATH_EXPLORE_LANDS = 'Oath: Explore Lands',
  OATH_UNITE_CLANS = 'Oath: Unite Clans',
  OATH_MASTER_CRAFT = 'Oath: Master Craft',
  OATH_COMMAND_ARMY = 'Oath: Command Army',
  OATH_DISCOVER_SECRETS = 'Oath: Discover Secrets',
  OATH_ESTABLISH_SHRINE = 'Oath: Establish Shrine',
  OATH_CONTROL_ROUTE = 'Oath: Control Route',
  OATH_AMASS_TREASURE = 'Oath: Amass Treasure',
  OATH_LEAD_EXPEDITION = 'Oath: Lead Expedition',
  OATH_FORGE_ALLIANCE = 'Oath: Forge Alliance',
  OATH_MASTER_SORCERY = 'Oath: Master Sorcery',
  OATH_TRAIN_WARRIORS = 'Oath: Train Warriors',
  OATH_BUILD_BRIDGE = 'Oath: Build Bridge',
  OATH_SETTLE_VALLEY = 'Oath: Settle Valley',
  OATH_GATHER_KNOWLEDGE = 'Oath: Gather Knowledge',
  OATH_DOMINATE_REGION = 'Oath: Dominate Region',
  OATH_ESTABLISH_MARKET = 'Oath: Establish Market',
  OATH_TAME_WILDERNESS = 'Oath: Tame Wilderness',
  OATH_BECOME_LEGEND = 'Oath: Become Legend',
  OATH_ACHIEVE_GREATNESS = 'Oath: Achieve Greatness',

  // Tier 3 - Hard (7-8 PV) - 25 cards
  OATH_CONQUER_KINGDOM = 'Oath: Conquer Kingdom',
  OATH_BUILD_EMPIRE = 'Oath: Build Empire',
  OATH_RULE_CONTINENT = 'Oath: Rule Continent',
  OATH_COMMAND_FLEETS = 'Oath: Command Fleets',
  OATH_CONTROL_MAGIC = 'Oath: Control Magic',
  OATH_RESHAPE_WORLD = 'Oath: Reshape World',
  OATH_ACHIEVE_IMMORTALITY = 'Oath: Achieve Immortality',
  OATH_MASTER_ELEMENTS = 'Oath: Master Elements',
  OATH_BUILD_MONUMENT = 'Oath: Build Monument',
  OATH_CONTROL_DESTINY = 'Oath: Control Destiny',
  OATH_UNITE_KINGDOMS = 'Oath: Unite Kingdoms',
  OATH_ESTABLISH_DYNASTY = 'Oath: Establish Dynasty',
  OATH_TRANSCEND_MORTALITY = 'Oath: Transcend Mortality',
  OATH_ACHIEVE_DIVINITY = 'Oath: Achieve Divinity',
  OATH_MASTER_ALL_ARTS = 'Oath: Master All Arts',
  OATH_CONTROL_ALL_ROUTES = 'Oath: Control All Routes',
  OATH_AMASS_INFINITE_WEALTH = 'Oath: Amass Infinite Wealth',
  OATH_COMMAND_ALL_ARMIES = 'Oath: Command All Armies',
  OATH_BECOME_IMMORTAL_LEGEND = 'Oath: Become Immortal Legend',
  OATH_RESHAPE_CIVILIZATION = 'Oath: Reshape Civilization',
  OATH_ACHIEVE_PERFECT_RULE = 'Oath: Achieve Perfect Rule',
  OATH_CONTROL_ALL_MAGIC = 'Oath: Control All Magic',
  OATH_TRANSCEND_LIMITS = 'Oath: Transcend Limits',
  OATH_MASTER_FORBIDDEN_ARTS = 'Oath: Master Forbidden Arts',
  OATH_ACHIEVE_ULTIMATE_POWER = 'Oath: Achieve Ultimate Power',

  // Tier 4 - Very Hard (9-10 PV) - 10 cards
  OATH_ASCEND_GODHOOD = 'Oath: Ascend Godhood',
  OATH_UNMAKE_WORLD = 'Oath: Unmake World',
  OATH_REMAKE_CREATION = 'Oath: Remake Creation',
  OATH_CLAIM_INFINITE_POWER = 'Oath: Claim Infinite Power',
  OATH_BECOME_ETERNAL = 'Oath: Become Eternal',
  OATH_SURPASS_ALL_MORTALS = 'Oath: Surpass All Mortals',
  OATH_CONTROL_FATE = 'Oath: Control Fate',
  OATH_MASTER_REALITY = 'Oath: Master Reality',
  OATH_ACHIEVE_OMNISCIENCE = 'Oath: Achieve Omniscience',
  OATH_BECOME_ONE_WITH_COSMOS = 'Oath: Become One with Cosmos',
}

export const ALL_OATHS = Object.values(OathName);
