export enum Tag {
    CONSTRUÇÃO = 'construção',
    MARÍTIMO = 'marítimo',
    ERUDIÇÃO = 'erudição',
    PODER = 'poder',
    DIPLOMACIA = 'diplomacia',
    ENGENHO = 'engenho',
    COMÉRCIO = 'comércio',
    AGRICULTURA = 'agricultura',
    BRUXARIA = 'bruxaria',
    PECUÁRIA = 'pecuária',
    FEUDO = 'feudo',
    MOON = 'moon',
    MARS = 'mars',
    HISTÓRIA = 'história',
    // Out-of-scope tags (kept for backward compatibility with existing cards)
    CRIME = 'crime',
    WILD = 'wild',
    CLONE = 'clone',
}

export const ALL_TAGS = [
  Tag.CONSTRUÇÃO,
  Tag.MARÍTIMO,
  Tag.ERUDIÇÃO,
  Tag.PODER,
  Tag.DIPLOMACIA,
  Tag.ENGENHO,
  Tag.COMÉRCIO,
  Tag.MOON,
  Tag.MARS,
  Tag.AGRICULTURA,
  Tag.BRUXARIA,
  Tag.PECUÁRIA,
  Tag.HISTÓRIA,
  Tag.FEUDO,
  Tag.CRIME,
  Tag.WILD,
  Tag.CLONE,
] as const;
